<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'AgvValidator\Module'             => __DIR__ . '/Module.php',
  'AgvValidator\Validator\Cnpj'     => __DIR__ . '/src/AgvValidator/Validator/Cnpj.php',
  'AgvValidator\Validator\Cpf'      => __DIR__ . '/src/AgvValidator/View/Helper/Cpf.php',
  'AgvValidator\View\Helper\Cnpj'   => __DIR__ . '/src/AgvValidator/View/Helper/Cnpj.php',
  'AgvValidator\Validator\CnpjTest' => __DIR__ . '/tests/AgvValidator/Validator/CnpjTest.php',
  'AgvValidator\Validator\CpfTest'  => __DIR__ . '/tests/AgvValidator/Validator/CpfTest.php',
  'Bootstrap'                       => __DIR__ . '/tests/Bootstrap.php',
);
